#server:
 # port: 8080
spring:
  application:
    name: fingerprint-api
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/replicacion_server
    url: jdbc:mysql://localhost:3306/replicacion
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#app:
 # sync:
  #  enable: true